name: Check Branch

on:
  push:
    branches:
      - main

jobs:
  branch_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'features'
        run: |
          echo "ERROR: You can only merge to main from features."
          exit 1

  deploy:
    needs: branch_validation
    name: Deploy to cinesync on stage branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Rsync to cinesync
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          path: .
          remote_path: ${{ secrets.TARGET_DIR_STAGE }}
          remote_host: ${{ secrets.HOST_DNS }}
          remote_port: ${{ secrets.HOST_PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.KEY }}
