name: Check Branch

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'features'
        run: |
          echo "ERROR: You can only merge to main from features."
          exit 1
